### ISSUE TITLE
Invalid ARN for Secret

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [ninthnails/terraform-aws-influxdb-oss#1]
Hi! Thanks so much for putting all this together!

I noticed that this line results in an invalid arn of the form `arn:aws:secretsmanager:us-east-2:<account_id>:secrets/influxdb_development_admin_password`
https://github.com/ninthnails/terraform-aws-influxdb-oss/blob/d86a2c26c3110df021fce336f463f5d8c4a534ce/main.tf#L228

Instead of `secrets/<name>` it should be `secret:<name>`. I was able to fix it by substituting with this line

```terraform
"arn:aws:secretsmanager:${data.aws_region.this.name}:${data.aws_caller_identity.this.account_id}:secret:${regex("secrets/(.*)", var.admin_password)[0]}"
```

Let me know if you'd like a PR with this and probably a fix for the SSM version as well. Happy to contribute!

**Comment by ninthnails** [comment]
Hello @rafmagns-skepa-dreag !
Thank you for reporting this. I would be happy to accept a PR fixing this.
